const test=require('node:test'),assert=require('node:assert/strict'),U=require('../data-updates.js');
const old='a'.repeat(64),latest='b'.repeat(64);
function setup({receipt=latest,refresh=async()=>latest,networkError=false}={}){const timers=[],events={},docEvents={},notices=[],calls=[];const env={location:{href:'https://example.test/site/'},document:{visibilityState:'visible',addEventListener:(k,f)=>docEvents[k]=f,removeEventListener:k=>delete docEvents[k]},addEventListener:(k,f)=>events[k]=f,removeEventListener:k=>delete events[k],setTimeout:(f,n)=>{timers.push({f,n});return timers.length;},clearTimeout(){},fetch:async()=>{calls.push('receipt');if(networkError)throw Error('offline');return{ok:true,json:async()=>({version:1,vaultSha256:receipt})};}};let downloads=0;const api=U.install({env,initialSha:old,notify:n=>notices.push(n),refresh:async s=>{downloads++;return refresh(s)}});return {api,env,timers,events,notices,calls,get downloads(){return downloads}};}
const settled=()=>new Promise(setImmediate);
test('a changed release replaces the stale session once; repeated checks fetch only tiny receipt',async()=>{const f=setup();await settled();assert.equal(f.downloads,1);assert.equal(f.notices.at(-1),'current');await f.api.check(true);assert.equal(f.downloads,1);assert.equal(f.calls.length,2)});
test('failed download stays stale and retries automatically rather than reporting current',async()=>{let attempts=0;const f=setup({refresh:async()=>{if(++attempts===1)throw Error('timeout');return latest;}});await settled();assert.equal(f.notices.at(-1),'offline');assert.equal(f.timers.at(-1).n,60000);await f.timers.at(-1).f();assert.equal(f.downloads,2);assert.equal(f.notices.at(-1),'current')});
test('network recovery triggers check; a locked page never accepts a late result',async()=>{let finish;const f=setup({refresh:()=>new Promise(r=>finish=r)});await settled();assert.equal(typeof f.events.online,'function');f.api.stop();finish(latest);await settled();assert.notEqual(f.notices.at(-1),'current');assert.equal(f.events.online,undefined)});
test('unchanged or offline receipts do not re-download large files',async()=>{const f=setup({receipt:old});await settled();assert.equal(f.downloads,0);const offline=setup({networkError:true});await settled();assert.equal(offline.downloads,0);assert.equal(offline.notices.at(-1),'offline')});
test('latest date advances after update while intentionally selected history is preserved',()=>{assert.equal(U.followDate('2026-09-30','2026-09-30','2026-10-09'),'2026-10-09');assert.equal(U.followDate('2026-09-29','2026-09-30','2026-10-09'),'2026-09-29')});
