const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const code=fs.readFileSync(require('node:path').join(__dirname,'../vault-cache.js'),'utf8');
const valid={version:1,cipher:'AES-256-GCM',kdf:'PBKDF2-SHA256',iterations:600000,compression:'gzip',salt:Buffer.alloc(32,1).toString('base64'),iv:Buffer.alloc(12,2).toString('base64'),data:Buffer.alloc(40,3).toString('base64')};
function fixture(){let saved=null,network;const calls=[];
 const cache={match:async()=>saved?.clone(),put:async(u,r)=>{saved=r.clone();}};
 const c=vm.createContext({atob,URL,location:{href:'https://example.test/site/'},Response,AbortController,setTimeout,clearTimeout,caches:{open:async()=>cache,delete:async()=>{saved=null;return true;}},fetch:async(u,o)=>{calls.push({u,o});return network(u,o);}});vm.runInContext(code,c);
 return {loader:c.DashboardVault,c,cache,calls,set network(fn){network=fn;},get saved(){return saved;},seed(){saved=new Response(JSON.stringify(valid),{headers:{etag:'"v1"','x-dashboard-cached-at':'2026-09-18'}});}};
}
test('first download stays candidate until decrypt succeeds; next visit 304 transfers no body',async()=>{const f=fixture();f.network=async()=>new Response(JSON.stringify(valid),{headers:{etag:'"v1"'}});const a=await f.loader.load();assert.equal(f.saved,null);await a.persist();assert.ok(f.saved);f.network=async(u,o)=>{assert.equal(o.headers['If-None-Match'],'"v1"');return new Response(null,{status:304});};const b=await f.loader.load();assert.equal(b.source,'cache');assert.deepEqual(JSON.parse(JSON.stringify(b.vault)),valid);});
test('new version replaces old only after successful decrypt, wrong password retains old',async()=>{const f=fixture();f.seed();f.network=async()=>new Response(JSON.stringify({...valid,data:Buffer.alloc(40,4).toString('base64')}),{headers:{etag:'"v2"'}});const a=await f.loader.load();assert.equal(f.saved.headers.get('etag'),'"v1"');await a.persist();assert.equal(f.saved.headers.get('etag'),'"v2"');});
test('network error and 503 explicitly flag stale cached data',async()=>{const f=fixture();f.seed();f.network=async()=>{throw Error('offline');};assert.equal((await f.loader.load()).source,'offline');f.network=async()=>new Response('',{status:503});assert.equal((await f.loader.load()).source,'offline');});
test('404 and corrupt 200 never silently use or overwrite old data',async()=>{const f=fixture();f.seed();f.network=async()=>new Response('',{status:404});await assert.rejects(f.loader.load(),/404/);f.network=async()=>new Response('<html>bad</html>');await assert.rejects(f.loader.load(),/不完整/);assert.equal(f.saved.headers.get('etag'),'"v1"');});
test('blocked persistent cache uses HTTP revalidation and quota failures do not block unlock',async()=>{const f=fixture();f.c.caches.open=async()=>{throw Error('blocked');};f.network=async(u,o)=>{assert.equal(o.cache,'no-cache');return new Response(JSON.stringify(valid));};const r=await f.loader.load();assert.equal(await r.persist(),false);const q=fixture();q.cache.put=async()=>{throw Error('quota');};q.network=async()=>new Response(JSON.stringify(valid));assert.equal(await (await q.loader.load()).persist(),false);});
test('no cache and network failure fails; orphan 304 fails; clear removes only named ciphertext cache',async()=>{const f=fixture();f.network=async()=>{throw Error('offline');};await assert.rejects(f.loader.load(),/没有可用缓存/);f.network=async()=>new Response(null,{status:304});await assert.rejects(f.loader.load(),/校验异常/);f.seed();assert.equal(await f.loader.clear(),true);assert.equal(f.saved,null);});
